# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=250)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('visibility', models.CharField(choices=[('pub', 'Public Event'), ('pri', 'Private Event'), ('rso', 'RSO Event')], default='pub', max_length=3)),
                ('category', models.CharField(choices=[('gen', 'General'), ('fun', 'Fund Raising'), ('soc', 'Social'), ('tec', 'Tech Talk')], default='gen', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RsoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMe', models.TextField()),
                ('member', models.ManyToManyField(blank=True, to='rso.RsoGroup')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('numStudents', models.IntegerField(verbose_name='Number of Student')),
                ('address', models.CharField(max_length=250)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rso.University'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsogroup',
            name='students',
            field=models.ManyToManyField(related_name='students', to='rso.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rso', to='rso.RsoGroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='rso.University'),
        ),
        migrations.AddField(
            model_name='admin',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='rso.Student'),
        ),
    ]
