# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rsogroup',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
