# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0002_auto_20170709_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='rsogroup',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
