# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0003_auto_20170709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
