# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0004_auto_20170709_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='university',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='university',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
    ]
