# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0006_auto_20170709_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='member',
            field=models.ManyToManyField(to='rso.RsoGroup'),
        ),
    ]
