# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0009_auto_20170709_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsogroup',
            old_name='users',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
