# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0009_auto_20170709_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsogroup',
            name='users',
        ),
        migrations.AddField(
            model_name='rsogroup',
            name='students',
            field=models.ManyToManyField(to='rso.Student'),
        ),
    ]
