# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0010_auto_20170716_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admin',
        ),
        migrations.AlterField(
            model_name='admin',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='rso.Student'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rso', to='rso.RsoGroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='rso.University'),
        ),
        migrations.AlterField(
            model_name='rsogroup',
            name='students',
            field=models.ManyToManyField(related_name='students', to='rso.Student'),
        ),
    ]
